made pre-commit more forgiving

diff --git a/.scripts/pre-commit b/.scripts/pre-commit
--- a/.scripts/pre-commit
+++ b/.scripts/pre-commit
@@ -22,12 +22,15 @@ if [ "$status" = 0 ] ; then
     #Exit
     exit 0
 else
-    echo "*********************************************************"
-    echo "       ********************************************      "
-    echo 1>&2 "Spotless Apply found violations it could not fix."
-    echo "Run spotless apply in your terminal and fix the issues before trying to commit again."
-    echo "       ********************************************      "
-    echo "*********************************************************"
-    #Exit
-    exit 1
+      echo "Static analysis found some problems (maybe your code has some syntax issues?)"
+      echo "We'll ignore it for now but please try to fix it :pleading:"
+      exit 0
+#     echo "*********************************************************"
+#     echo "       ********************************************      "
+#     echo 1>&2 "Spotless Apply found violations it could not fix."
+#     echo "Run spotless apply in your terminal and fix the issues before trying to commit again."
+#     echo "       ********************************************      "
+#     echo "*********************************************************"
+#     #Exit
+#     exit 1
 fi
